# Trabalhando com a biblioteca Numpy

In [1]:
import numpy as np

## criando um array unidimensional com o metodo `.array()` 

In [3]:
n1 = np.array([1, 2, 3, 4, 5, 6])
n1

array([1, 2, 3, 4, 5, 6])

## criando um array multidimensional com o método `.array()`

In [4]:
n2 = np.array([[1, 2, 3, 4, 5, 6], [10, 20, 30, 40, 50, 60]])
n2

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

## criando uma array multidmensional prenchido por zeros como metodo `.zeros()`

In [5]:
n3 = np.zeros((2,2))
n3

array([[0., 0.],
       [0., 0.]])

### também podemos passar outros parâmetros

In [6]:
n4 =np.zeros(shape=(5,5), dtype="int")
n4

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## criando uma array preenchido com o valor determindo usando o metdo `.full()`

In [7]:
n5 = np.full(shape=(6,6), fill_value=10, dtype="int")
n5 

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [8]:
n6 = np.full((4,4), 7, "int")
n6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## Criando arrays a partir de um intervalo e prenchendo automáticamente pelos valores do intervalo, utilizando o método `.arange()` 

In [11]:
n7 = np.arange(10, 90)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

### podemos também definil os passos no intervalo

In [12]:
n8 = np.arange(start=5, stop=500, step= 10)
n8

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125,
       135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255,
       265, 275, 285, 295, 305, 315, 325, 335, 345, 355, 365, 375, 385,
       395, 405, 415, 425, 435, 445, 455, 465, 475, 485, 495])

# criando e preenchendo um array com de forma aleatórtia com o método `random.randint()`

In [13]:
n9 = np.random.randint(10, 100, 8)
n9

array([71, 68, 40, 72, 67, 90, 81, 21])

In [14]:
n10 = np.random.randint(low=8, high=8000, size=100)
n10

array([1327, 1489, 7039, 4331, 3584, 5996, 4675,  614, 4834, 1010, 1416,
       6123, 1650, 1073, 6592, 1895, 7261, 1122, 5000, 4777, 5636, 4144,
       7572, 1585, 3898, 4777, 1080, 6352, 7311, 2733, 4675, 5663, 6184,
        943, 5272, 5455, 3697,  722, 6891, 1013, 3494,   42, 1079, 3855,
       1629, 3608, 4767, 4671, 4365, 4406, 2531, 5246, 7424, 4702, 6020,
       6125, 3952, 3526, 3338, 4879, 5180, 5893,   73, 5048,  789, 3780,
       4982, 1771,  286,  460, 3692, 2376, 1001, 3943, 7225, 2184, 2264,
       1887, 4545, 5025, 3170,  386, 2856,  938, 1729, 6629, 7291, 7385,
       2216, 2584, 1830, 1647, 2239, 3315, 2989,  747, 3349, 6139, 3090,
       4283])

## calculando a dimensão de um array com o metodo `.shape`

In [15]:
n11 = np.array([[1, 2, 3], [4, 5, 6]])
n11

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(n11.shape)

(2, 3)


### trocando ou atribuindo uma nova dimensão na array

In [20]:
n11.shape = (3, 2)
n11.shape
n11

array([[1, 2],
       [3, 4],
       [5, 6]])