# Unindo array com metodos do numpy

In [1]:
import numpy as np

In [2]:
n1 = np.array([10, 20, 30])
n2 = np.array([40, 50, 60])


In [4]:
np.vstack((n1, n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
np.hstack((n1, n2))

array([10, 20, 30, 40, 50, 60])

In [9]:
np.column_stack((n1, n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

## realizando operações com array de uma dimensão

In [10]:
a = np.array([10, 20, 30, 50 , 12, 15])
b = np.array([12, 15, 77, 34, 50])

In [13]:
np.intersect1d(a, b)

array([12, 15, 50])

In [14]:
np.setdiff1d(n1, n2)

array([10, 20, 30])

In [15]:
np.setdiff1d(n2, n1)

array([40, 50, 60])

In [19]:
sum_ = np.sum([n1, n2])
print(f" sum of all elements betwen {n1} and {n2} is: {sum_}")

 sum of all elements betwen [10 20 30] and [40 50 60] is: 210


In [20]:
np.sum(a=[n1,n2], axis=0)

array([50, 70, 90])

In [21]:
np.sum([n1, n2], axis=1)


array([ 60, 150])

In [26]:
array = list([1, 2, 3])
array_numpy = np.array([2, 3, 4, 5])

sum_2 = array_numpy + 1

print(type(array), type(array_numpy))
print(sum_2)

<class 'list'> <class 'numpy.ndarray'>
[3 4 5 6]


In [27]:
n1 + 20

array([30, 40, 50])

In [28]:
n1 * 2

array([20, 40, 60])

In [29]:
n1 - 10

array([ 0, 10, 20])

In [30]:
n1 / 10

array([1., 2., 3.])

## mais operações 

### calculando a média

In [31]:
new_array = np.array([10, 35, 26, 87, 10, 56, 13, 45, 66])

In [36]:
np.mean(new_array)

38.666666666666664

### calculando a mediana

In [37]:
np.median(new_array)

35.0

### calculando a divisão padrão

In [38]:
np.std(new_array)

25.603819159562025

## salvando e lendo arrays numpy om os métodos `.save()` e `.load()`

In [39]:
array_2 = np.array([12, 3, 4, 56, 12, 34, 89])

In [41]:
import os 

directory = "numpy-data"
if not os.path.exists(directory):
    os.makedirs(directory)

np.save(f"{directory}/numpy_array_1", array_2)

In [46]:
try:
    array_3 = np.load(f"{directory}/numpy_array_1.npy")
    
    print(array_3)
except FileNotFoundError as err:
    print(f"ficheiro não econtrado: {err}")

[12  3  4 56 12 34 89]
